Map<String, String> currencyValues = <String, String>{
  'Afghanistan': 'AFN',
  'Albania': 'ALL',
  'Algeria': 'DZD',
  'AmericanSamoa': 'USD',
  'Andorra': 'EUR',
  'Angola': 'AOA',
  'Anguilla': 'XCD',
  'Antarctica': '',
  'Antigua and Barbuda': 'XCD',
  'Argentina': 'ARS',
  'Armenia': 'AMD',
  'Aruba': 'AWG',
  'Australia': 'AUD',
  'Austria': 'EUR',
  'Azerbaijan': 'AZN',
  'Bahamas (The)': 'BSD',
  'Bahrain': 'BHD',
  'Bangladesh': 'BDT',
  'Barbados': 'BBD',
  'Belarus': 'BYN',
  'Belgium': 'EUR',
  'Belize': 'BZD',
  'Benin': 'XOF',
  'Bermuda': 'BMD',
  'Bhutan': 'BTN',
  'Bhutan (Indian Rupee)': 'INR',
  'Bolivia, Plurinational State of': 'BOB',
  'Bolivia (Plurinational State of) (Mvdol)': 'BOV',
  'Bonaire, Sint Eustatius and Saba': 'USD',
  'Bosnia and Herzegovina': 'BAM',
  'Botswana': 'BWP',
  'Bouvet Island': 'NOK',
  'Brazil': 'BRL',
  'British Indian Ocean Territory': 'USD',
  'Brunei Darussalam': 'BND',
  'Bulgaria': 'BGN',
  'Burkina Faso': 'XOF',
  'Burundi': 'BIF',
  'Cabo Verde': 'CVE',
  'Cambodia': 'KHR',
  'Cameroon': 'XAF',
  'Canada': 'CAD',
  'Cayman Islands (The)': 'KYD',
  'Central African Republic': 'XAF',
  'Chad': 'XAF',
  'Chile (Unidad de Fomento)': 'CLF',
  'Chile (Chilean Peso)': 'CLP',
  'China': 'CNY',
  'Christmas Island': 'AUD',
  'Cocos (Keeling) Islands': 'AUD',
  'Colombia': 'COP',
  'Comoros': 'KMF',
  'Congo, The Democratic Republic of the Congo': 'CDF',
  'Congo': 'XAF',
  'Cook Islands': 'NZD',
  'Costa Rica': 'CRC',
  'Croatia': 'EUR',
  'Cuba': 'CUP',
  'Curaçao': 'ANG',
  'Cyprus': 'EUR',
  'Czech Republic': 'CZK',
  "Cote d'Ivoire": 'XOF',
  'Denmark': 'DKK',
  'Djibouti': 'DJF',
  'Dominica': 'XCD',
  'Dominican Republic (The)': 'DOP',
  'Ecuador': 'USD',
  'Egypt': 'EGP',
  'El Salvador': 'USD',
  'Equatorial Guinea': 'XAF',
  'Eritrea': 'ERN',
  'Estonia': 'EUR',
  'Ethiopia': 'ETB',
  'European Union': 'EUR',
  'Falkland Islands (Malvinas)': 'FKP',
  'Faroe Islands': 'DKK',
  'Fiji': 'FJD',
  'Finland': 'EUR',
  'France': 'EUR',
  'French Guiana': 'EUR',
  'French Polynesia': 'XPF',
  'French Southern Territories': 'EUR',
  'Gabon': 'XAF',
  'Gambia (The)': 'GMD',
  'Georgia': 'GEL',
  'Germany': 'EUR',
  'Ghana': 'GHS',
  'Gibraltar': 'GIP',
  'Greece': 'EUR',
  'Greenland': 'DKK',
  'Grenada': 'XCD',
  'Guadeloupe': 'EUR',
  'Guam': 'USD',
  'Guatemala': 'GTQ',
  'Guernsey': 'GBP',
  'Guinea': 'GNF',
  'Guinea-Bissau': 'XOF',
  'Guyana': 'GYD',
  'Haiti': 'HTG',
  'Heard Island and McDonald Islands': 'AUD',
  'Holy See (Vatican City State)': 'EUR',
  'Honduras': 'HNL',
  'Hong Kong': 'HKD',
  'Hungary': 'HUF',
  'Iceland': 'ISK',
  'India': 'INR',
  'Indonesia': 'IDR',
  'Iran, Islamic Republic of Persian Gulf': 'IRR',
  'Iraq': 'IQD',
  'Ireland': 'EUR',
  'Isle of Man': 'GBP',
  'Israel': 'ILS',
  'Italy': 'EUR',
  'Jamaica': 'JMD',
  'Japan': 'JPY',
  'Jersey': 'GBP',
  'Jordan': 'JOD',
  'Kazakhstan': 'KZT',
  'Kenya': 'KES',
  'Kiribati': 'AUD',
  'Korea, Democratic People’s Republic of Korea)': 'KPW',
  'Korea, Republic of South Korea': 'KRW',
  'Kuwait': 'KWD',
  'Kyrgyzstan': 'KGS',
  'Laos': 'LAK',
  'Latvia': 'EUR',
  'Lebanon': 'LBP',
  'Lesotho (Loti)': 'LSL',
  'Lesotho (Rand)': 'ZAR',
  'Liberia': 'LRD',
  'Libyan Arab Jamahiriya': 'LYD',
  'Liechtenstein': 'CHF',
  'Lithuania': 'EUR',
  'Luxembourg': 'EUR',
  'Macao': 'MOP',
  'Madagascar': 'MGA',
  'Malawi': 'MWK',
  'Malaysia': 'MYR',
  'Maldives': 'MVR',
  'Mali': 'XOF',
  'Malta': 'EUR',
  'Marshall Islands (The)': 'USD',
  'Martinique': 'EUR',
  'Mauritania': 'MRU',
  'Mauritius': 'MUR',
  'Mayotte': 'EUR',
  'Member Countries of the African Development Bank Group': 'XUA',
  'Mexico (Mexican Peso)': 'MXN',
  'Mexico (Mexican Unidad de Inversion - UDI)': 'MXV',
  'Micronesia, Federated States of Micronesia': 'USD',
  'Moldova': 'MDL',
  'Monaco': 'EUR',
  'Mongolia': 'MNT',
  'Montenegro': 'EUR',
  'Montserrat': 'XCD',
  'Morocco': 'MAD',
  'Mozambique': 'MZN',
  'Myanmar': 'MMK',
  'Namibia': 'NAD',
  'Nauru': 'AUD',
  'Nepal': 'NPR',
  'Netherlands (The)': 'EUR',
  'New Caledonia': 'XPF',
  'New Zealand': 'NZD',
  'Nicaragua': 'NIO',
  'Niger (The)': 'XOF',
  'Nigeria': 'NGN',
  'Niue': 'NZD',
  'Norfolk Island': 'AUD',
  'Northern Mariana Islands (The)': 'USD',
  'Norway': 'NOK',
  'Oman': 'OMR',
  'Pakistan': 'PKR',
  'Palau': 'USD',
  'Palestinian Territory, Occupied, State of': '',
  'Panama': 'PAB',
  'Papua New Guinea': 'PGK',
  'Paraguay': 'PYG',
  'Peru': 'PEN',
  'Philippines (The)': 'PHP',
  'Pitcairn': 'NZD',
  'Poland': 'PLN',
  'Portugal': 'EUR',
  'Puerto Rico': 'USD',
  'Qatar': 'QAR',
  'Republic of North Macedonia': 'MKD',
  'Romania': 'RON',
  'Russian Federation (The)': 'RUB',
  'Rwanda': 'RWF',
  'Réunion': 'EUR',
  'Saint Barthélemy': 'EUR',
  'Saint Helena, Ascension and Tristan da Cunha': 'SHP',
  'Saint Kitts and Nevis': 'XCD',
  'Saint Lucia': 'XCD',
  'Saint Martin (French Part)': 'EUR',
  'Saint Pierre and Miquelon': 'EUR',
  'Saint Vincent and the Grenadines': 'XCD',
  'Samoa': 'WST',
  'San Marino': 'EUR',
  'Sao Tome and Principe': 'STN',
  'Saudi Arabia': 'SAR',
  'Senegal': 'XOF',
  'Serbia': 'RSD',
  'Seychelles': 'SCR',
  'Sierra Leone': 'SLE',
  'Singapore': 'SGD',
  'Sint Maarten (Dutch Part)': 'ANG',
  'Sistema Unitario de Compensacion Regional de Pagos "Sucre"': 'XSU',
  'Slovakia': 'EUR',
  'Slovenia': 'EUR',
  'Solomon Islands': 'SBD',
  'Somalia': 'SOS',
  'South Africa': 'ZAR',
  'South Georgia and the South Sandwich Islands': '',
  'South Sudan': 'SSP',
  'Spain': 'EUR',
  'Sri Lanka': 'LKR',
  'Sudan (The)': 'SDG',
  'Suriname': 'SRD',
  'Svalbard and Jan Mayen': 'NOK',
  'Swaziland': 'SZL',
  'Sweden': 'SEK',
  'Switzerland (WIR Euro)': 'CHE',
  'Switzerland (Swiss Franc)': 'CHF',
  'Switzerland (WIR Franc)': 'CHW',
  'Syrian Arab Republic': 'SYP',
  'Taiwan (Province of China)': 'TWD',
  'Tajikistan': 'TJS',
  'Tanzania, United Republic of Tanzania': 'TZS',
  'Thailand': 'THB',
  'Timor-Leste': 'USD',
  'Togo': 'XOF',
  'Tokelau': 'NZD',
  'Tonga': 'TOP',
  'Trinidad and Tobago': 'TTD',
  'Tunisia': 'TND',
  'Turkey': 'TRY',
  'Turkmenistan': 'TMT',
  'Turks and Caicos Islands': 'USD',
  'Tuvalu': 'AUD',
  'Uganda': 'UGX',
  'Ukraine': 'UAH',
  'United Arab Emirates (The)': 'AED',
  'United Kingdom': 'GBP',
  'United States': 'USD',
  'United States of America (The)': 'USD',
  'United States of America (The) (US Dollar Next day)': 'USN',
  'Uruguay (Uruguay Peso en Unidades Indexadas - URUIURUI)': 'UYI',
  'Uruguay (Peso Uruguayo)': 'UYU',
  'Uzbekistan': 'UZS',
  'Vanuatu': 'VUV',
  'Venezuela, Bolivarian Republic of Venezuela': 'VEF',
  'Venezuela (Bolivarian Republic of)': 'VED',
  'Vietnam': 'VND',
  'Virgin Islands, British': 'USD',
  'Virgin Islands, U.S.': 'USD',
  'Wallis and Futuna': 'XPF',
  'Western Sahara': 'MAD',
  'Yemen': 'YER',
  'Zambia': 'ZMW',
  'Zimbabwe': 'ZWL',
  'Aland Islands': 'EUR',
};
