// Map<String, String> currencyValues = <String, String>{
//   'Afghanistan': 'AFN',
//   'Albania': 'ALL',
//   'Algeria': 'DZD',
//   'AmericanSamoa': 'USD',
//   'Andorra': 'EUR',
//   'Angola': 'AOA',
//   'Anguilla': 'XCD',
//   'Antarctica': '',
//   'Antigua and Barbuda': 'XCD',
//   'Argentina': 'ARS',
//   'Armenia': 'AMD',
//   'Aruba': 'AWG',
//   'Australia': 'AUD',
//   'Austria': 'EUR',
//   'Azerbaijan': 'AZN',
//   'Bahamas (The)': 'BSD',
//   'Bahrain': 'BHD',
//   'Bangladesh': 'BDT',
//   'Barbados': 'BBD',
//   'Belarus': 'BYN',
//   'Belgium': 'EUR',
//   'Belize': 'BZD',
//   'Benin': 'XOF',
//   'Bermuda': 'BMD',
//   'Bhutan': 'BTN',
//   'Bhutan (Indian Rupee)': 'INR',
//   'Bolivia, Plurinational State of': 'BOB',
//   'Bolivia (Plurinational State of) (Mvdol)': 'BOV',
//   'Bonaire, Sint Eustatius and Saba': 'USD',
//   'Bosnia and Herzegovina': 'BAM',
//   'Botswana': 'BWP',
//   'Bouvet Island': 'NOK',
//   'Brazil': 'BRL',
//   'British Indian Ocean Territory': 'USD',
//   'Brunei Darussalam': 'BND',
//   'Bulgaria': 'BGN',
//   'Burkina Faso': 'XOF',
//   'Burundi': 'BIF',
//   'Cabo Verde': 'CVE',
//   'Cambodia': 'KHR',
//   'Cameroon': 'XAF',
//   'Canada': 'CAD',
//   'Cayman Islands (The)': 'KYD',
//   'Central African Republic': 'XAF',
//   'Chad': 'XAF',
//   'Chile (Unidad de Fomento)': 'CLF',
//   'Chile (Chilean Peso)': 'CLP',
//   'China': 'CNY',
//   'Christmas Island': 'AUD',
//   'Cocos (Keeling) Islands': 'AUD',
//   'Colombia': 'COP',
//   'Comoros': 'KMF',
//   'Congo, The Democratic Republic of the Congo': 'CDF',
//   'Congo': 'XAF',
//   'Cook Islands': 'NZD',
//   'Costa Rica': 'CRC',
//   'Croatia': 'EUR',
//   'Cuba': 'CUP',
//   'Curaçao': 'ANG',
//   'Cyprus': 'EUR',
//   'Czech Republic': 'CZK',
//   "Cote d'Ivoire": 'XOF',
//   'Denmark': 'DKK',
//   'Djibouti': 'DJF',
//   'Dominica': 'XCD',
//   'Dominican Republic (The)': 'DOP',
//   'Ecuador': 'USD',
//   'Egypt': 'EGP',
//   'El Salvador': 'USD',
//   'Equatorial Guinea': 'XAF',
//   'Eritrea': 'ERN',
//   'Estonia': 'EUR',
//   'Ethiopia': 'ETB',
//   'European Union': 'EUR',
//   'Falkland Islands (Malvinas)': 'FKP',
//   'Faroe Islands': 'DKK',
//   'Fiji': 'FJD',
//   'Finland': 'EUR',
//   'France': 'EUR',
//   'French Guiana': 'EUR',
//   'French Polynesia': 'XPF',
//   'French Southern Territories': 'EUR',
//   'Gabon': 'XAF',
//   'Gambia (The)': 'GMD',
//   'Georgia': 'GEL',
//   'Germany': 'EUR',
//   'Ghana': 'GHS',
//   'Gibraltar': 'GIP',
//   'Greece': 'EUR',
//   'Greenland': 'DKK',
//   'Grenada': 'XCD',
//   'Guadeloupe': 'EUR',
//   'Guam': 'USD',
//   'Guatemala': 'GTQ',
//   'Guernsey': 'GBP',
//   'Guinea': 'GNF',
//   'Guinea-Bissau': 'XOF',
//   'Guyana': 'GYD',
//   'Haiti': 'HTG',
//   'Heard Island and McDonald Islands': 'AUD',
//   'Holy See (Vatican City State)': 'EUR',
//   'Honduras': 'HNL',
//   'Hong Kong': 'HKD',
//   'Hungary': 'HUF',
//   'Iceland': 'ISK',
//   'India': 'INR',
//   'Indonesia': 'IDR',
//   'Iran, Islamic Republic of Persian Gulf': 'IRR',
//   'Iraq': 'IQD',
//   'Ireland': 'EUR',
//   'Isle of Man': 'GBP',
//   'Israel': 'ILS',
//   'Italy': 'EUR',
//   'Jamaica': 'JMD',
//   'Japan': 'JPY',
//   'Jersey': 'GBP',
//   'Jordan': 'JOD',
//   'Kazakhstan': 'KZT',
//   'Kenya': 'KES',
//   'Kiribati': 'AUD',
//   'Korea, Democratic People’s Republic of Korea)': 'KPW',
//   'Korea, Republic of South Korea': 'KRW',
//   'Kuwait': 'KWD',
//   'Kyrgyzstan': 'KGS',
//   'Laos': 'LAK',
//   'Latvia': 'EUR',
//   'Lebanon': 'LBP',
//   'Lesotho (Loti)': 'LSL',
//   'Lesotho (Rand)': 'ZAR',
//   'Liberia': 'LRD',
//   'Libyan Arab Jamahiriya': 'LYD',
//   'Liechtenstein': 'CHF',
//   'Lithuania': 'EUR',
//   'Luxembourg': 'EUR',
//   'Macao': 'MOP',
//   'Madagascar': 'MGA',
//   'Malawi': 'MWK',
//   'Malaysia': 'MYR',
//   'Maldives': 'MVR',
//   'Mali': 'XOF',
//   'Malta': 'EUR',
//   'Marshall Islands (The)': 'USD',
//   'Martinique': 'EUR',
//   'Mauritania': 'MRU',
//   'Mauritius': 'MUR',
//   'Mayotte': 'EUR',
//   'Member Countries of the African Development Bank Group': 'XUA',
//   'Mexico (Mexican Peso)': 'MXN',
//   'Mexico (Mexican Unidad de Inversion - UDI)': 'MXV',
//   'Micronesia, Federated States of Micronesia': 'USD',
//   'Moldova': 'MDL',
//   'Monaco': 'EUR',
//   'Mongolia': 'MNT',
//   'Montenegro': 'EUR',
//   'Montserrat': 'XCD',
//   'Morocco': 'MAD',
//   'Mozambique': 'MZN',
//   'Myanmar': 'MMK',
//   'Namibia': 'NAD',
//   'Nauru': 'AUD',
//   'Nepal': 'NPR',
//   'Netherlands (The)': 'EUR',
//   'New Caledonia': 'XPF',
//   'New Zealand': 'NZD',
//   'Nicaragua': 'NIO',
//   'Niger (The)': 'XOF',
//   'Nigeria': 'NGN',
//   'Niue': 'NZD',
//   'Norfolk Island': 'AUD',
//   'Northern Mariana Islands (The)': 'USD',
//   'Norway': 'NOK',
//   'Oman': 'OMR',
//   'Pakistan': 'PKR',
//   'Palau': 'USD',
//   'Palestinian Territory, Occupied, State of': '',
//   'Panama': 'PAB',
//   'Papua New Guinea': 'PGK',
//   'Paraguay': 'PYG',
//   'Peru': 'PEN',
//   'Philippines (The)': 'PHP',
//   'Pitcairn': 'NZD',
//   'Poland': 'PLN',
//   'Portugal': 'EUR',
//   'Puerto Rico': 'USD',
//   'Qatar': 'QAR',
//   'Republic of North Macedonia': 'MKD',
//   'Romania': 'RON',
//   'Russian Federation (The)': 'RUB',
//   'Rwanda': 'RWF',
//   'Réunion': 'EUR',
//   'Saint Barthélemy': 'EUR',
//   'Saint Helena, Ascension and Tristan da Cunha': 'SHP',
//   'Saint Kitts and Nevis': 'XCD',
//   'Saint Lucia': 'XCD',
//   'Saint Martin (French Part)': 'EUR',
//   'Saint Pierre and Miquelon': 'EUR',
//   'Saint Vincent and the Grenadines': 'XCD',
//   'Samoa': 'WST',
//   'San Marino': 'EUR',
//   'Sao Tome and Principe': 'STN',
//   'Saudi Arabia': 'SAR',
//   'Senegal': 'XOF',
//   'Serbia': 'RSD',
//   'Seychelles': 'SCR',
//   'Sierra Leone': 'SLE',
//   'Singapore': 'SGD',
//   'Sint Maarten (Dutch Part)': 'ANG',
//   'Sistema Unitario de Compensacion Regional de Pagos "Sucre"': 'XSU',
//   'Slovakia': 'EUR',
//   'Slovenia': 'EUR',
//   'Solomon Islands': 'SBD',
//   'Somalia': 'SOS',
//   'South Africa': 'ZAR',
//   'South Georgia and the South Sandwich Islands': '',
//   'South Sudan': 'SSP',
//   'Spain': 'EUR',
//   'Sri Lanka': 'LKR',
//   'Sudan (The)': 'SDG',
//   'Suriname': 'SRD',
//   'Svalbard and Jan Mayen': 'NOK',
//   'Swaziland': 'SZL',
//   'Sweden': 'SEK',
//   'Switzerland (WIR Euro)': 'CHE',
//   'Switzerland (Swiss Franc)': 'CHF',
//   'Switzerland (WIR Franc)': 'CHW',
//   'Syrian Arab Republic': 'SYP',
//   'Taiwan (Province of China)': 'TWD',
//   'Tajikistan': 'TJS',
//   'Tanzania, United Republic of Tanzania': 'TZS',
//   'Thailand': 'THB',
//   'Timor-Leste': 'USD',
//   'Togo': 'XOF',
//   'Tokelau': 'NZD',
//   'Tonga': 'TOP',
//   'Trinidad and Tobago': 'TTD',
//   'Tunisia': 'TND',
//   'Turkey': 'TRY',
//   'Turkmenistan': 'TMT',
//   'Turks and Caicos Islands': 'USD',
//   'Tuvalu': 'AUD',
//   'Uganda': 'UGX',
//   'Ukraine': 'UAH',
//   'United Arab Emirates (The)': 'AED',
//   'United Kingdom': 'GBP',
//   'United States': 'USD',
//   'United States of America (The)': 'USD',
//   'United States of America (The) (US Dollar Next day)': 'USN',
//   'Uruguay (Uruguay Peso en Unidades Indexadas - URUIURUI)': 'UYI',
//   'Uruguay (Peso Uruguayo)': 'UYU',
//   'Uzbekistan': 'UZS',
//   'Vanuatu': 'VUV',
//   'Venezuela, Bolivarian Republic of Venezuela': 'VEF',
//   'Venezuela (Bolivarian Republic of)': 'VED',
//   'Vietnam': 'VND',
//   'Virgin Islands, British': 'USD',
//   'Virgin Islands, U.S.': 'USD',
//   'Wallis and Futuna': 'XPF',
//   'Western Sahara': 'MAD',
//   'Yemen': 'YER',
//   'Zambia': 'ZMW',
//   'Zimbabwe': 'ZWL',
//   'Aland Islands': 'EUR',
// };
Map<String, String> currencyValues = <String, String>{
  'Afghanistan': 'USD',
  'Albania': 'USD',
  'Algeria': 'USD',
  'AmericanSamoa': 'USD',
  'Andorra': 'USD',
  'Angola': 'USD',
  'Anguilla': 'USD',
  'Antarctica': 'USD',
  'Antigua and Barbuda': 'USD',
  'Argentina': 'USD',
  'Armenia': 'USD',
  'Aruba': 'USD',
  'Australia': 'USD',
  'Austria': 'USD',
  'Azerbaijan': 'USD',
  'Bahamas (The)': 'USD',
  'Bahrain': 'USD',
  'Bangladesh': 'USD',
  'Barbados': 'USD',
  'Belarus': 'USD',
  'Belgium': 'USD',
  'Belize': 'USD',
  'Benin': 'USD',
  'Bermuda': 'USD',
  'Bhutan': 'USD',
  'Bhutan (Indian Rupee)': 'USD',
  'Bolivia, Plurinational State of': 'USD',
  'Bolivia (Plurinational State of) (Mvdol)': 'USD',
  'Bonaire, Sint Eustatius and Saba': 'USD',
  'Bosnia and Herzegovina': 'USD',
  'Botswana': 'USD',
  'Bouvet Island': 'USD',
  'Brazil': 'USD',
  'British Indian Ocean Territory': 'USD',
  'Brunei Darussalam': 'USD',
  'Bulgaria': 'USD',
  'Burkina Faso': 'USD',
  'Burundi': 'USD',
  'Cabo Verde': 'USD',
  'Cambodia': 'USD',
  'Cameroon': 'USD',
  'Canada': 'USD',
  'Cayman Islands (The)': 'USD',
  'Central African Republic': 'USD',
  'Chad': 'USD',
  'Chile (Unidad de Fomento)': 'USD',
  'Chile (Chilean Peso)': 'USD',
  'China': 'USD',
  'Christmas Island': 'USD',
  'Cocos (Keeling) Islands': 'USD',
  'Colombia': 'USD',
  'Comoros': 'USD',
  'Congo, The Democratic Republic of the Congo': 'USD',
  'Congo': 'USD',
  'Cook Islands': 'USD',
  'Costa Rica': 'USD',
  'Croatia': 'USD',
  'Cuba': 'USD',
  'Curaçao': 'USD',
  'Cyprus': 'USD',
  'Czech Republic': 'USD',
  "Cote d'Ivoire": 'USD',
  'Denmark': 'USD',
  'Djibouti': 'USD',
  'Dominica': 'USD',
  'Dominican Republic (The)': 'USD',
  'Ecuador': 'USD',
  'Egypt': 'USD',
  'El Salvador': 'USD',
  'Equatorial Guinea': 'USD',
  'Eritrea': 'USD',
  'Estonia': 'USD',
  'Ethiopia': 'USD',
  'European Union': 'USD',
  'Falkland Islands (Malvinas)': 'USD',
  'Faroe Islands': 'USD',
  'Fiji': 'USD',
  'Finland': 'USD',
  'France': 'USD',
  'French Guiana': 'USD',
  'French Polynesia': 'USD',
  'French Southern Territories': 'USD',
  'Gabon': 'USD',
  'Gambia (The)': 'USD',
  'Georgia': 'USD',
  'Germany': 'USD',
  'Ghana': 'USD',
  'Gibraltar': 'USD',
  'Greece': 'USD',
  'Greenland': 'USD',
  'Grenada': 'USD',
  'Guadeloupe': 'USD',
  'Guam': 'USD',
  'Guatemala': 'USD',
  'Guernsey': 'USD',
  'Guinea': 'USD',
  'Guinea-Bissau': 'USD',
  'Guyana': 'USD',
  'Haiti': 'USD',
  'Heard Island and McDonald Islands': 'USD',
  'Holy See (Vatican City State)': 'USD',
  'Honduras': 'USD',
  'Hong Kong': 'USD',
  'Hungary': 'USD',
  'Iceland': 'USD',
  'India': 'USD',
  'Indonesia': 'USD',
  'Iran, Islamic Republic of Persian Gulf': 'USD',
  'Iraq': 'USD',
  'Ireland': 'USD',
  'Isle of Man': 'USD',
  'Israel': 'USD',
  'Italy': 'USD',
  'Jamaica': 'USD',
  'Japan': 'USD',
  'Jersey': 'USD',
  'Jordan': 'USD',
  'Kazakhstan': 'USD',
  'Kenya': 'USD',
  'Kiribati': 'USD',
  'Korea, Democratic People’s Republic of Korea)': 'USD',
  'Korea, Republic of South Korea': 'USD',
  'Kuwait': 'USD',
  'Kyrgyzstan': 'USD',
  'Laos': 'USD',
  'Latvia': 'USD',
  'Lebanon': 'USD',
  'Lesotho (Loti)': 'USD',
  'Lesotho (Rand)': 'USD',
  'Liberia': 'USD',
  'Libyan Arab Jamahiriya': 'USD',
  'Liechtenstein': 'USD',
  'Lithuania': 'USD',
  'Luxembourg': 'USD',
  'Macao': 'USD',
  'Madagascar': 'USD',
  'Malawi': 'USD',
  'Malaysia': 'USD',
  'Maldives': 'USD',
  'Mali': 'USD',
  'Malta': 'USD',
  'Marshall Islands (The)': 'USD',
  'Martinique': 'USD',
  'Mauritania': 'USD',
  'Mauritius': 'USD',
  'Mayotte': 'USD',
  'Member Countries of the African Development Bank Group': 'USD',
  'Mexico (Mexican Peso)': 'USD',
  'Mexico (Mexican Unidad de Inversion - UDI)': 'USD',
  'Micronesia, Federated States of Micronesia': 'USD',
  'Moldova': 'USD',
  'Monaco': 'USD',
  'Mongolia': 'USD',
  'Montenegro': 'USD',
  'Montserrat': 'USD',
  'Morocco': 'USD',
  'Mozambique': 'USD',
  'Myanmar': 'USD',
  'Namibia': 'USD',
  'Nauru': 'USD',
  'Nepal': 'USD',
  'Netherlands (The)': 'USD',
  'New Caledonia': 'USD',
  'New Zealand': 'USD',
  'Nicaragua': 'USD',
  'Niger (The)': 'USD',
  'Nigeria': 'USD',
  'Niue': 'USD',
  'Norfolk Island': 'USD',
  'Northern Mariana Islands (The)': 'USD',
  'Norway': 'USD',
  'Oman': 'USD',
  'Pakistan': 'USD',
  'Palau': 'USD',
  'Palestinian Territory, Occupied, State of': 'USD',
  'Panama': 'USD',
  'Papua New Guinea': 'USD',
  'Paraguay': 'USD',
  'Peru': 'USD',
  'Philippines (The)': 'USD',
  'Pitcairn': 'USD',
  'Poland': 'USD',
  'Portugal': 'USD',
  'Puerto Rico': 'USD',
  'Qatar': 'USD',
  'Republic of North Macedonia': 'USD',
  'Romania': 'USD',
  'Russian Federation (The)': 'USD',
  'Rwanda': 'USD',
  'Réunion': 'USD',
  'Saint Barthélemy': 'USD',
  'Saint Helena, Ascension and Tristan da Cunha': 'USD',
  'Saint Kitts and Nevis': 'USD',
  'Saint Lucia': 'USD',
  'Saint Martin (French Part)': 'USD',
  'Saint Pierre and Miquelon': 'USD',
  'Saint Vincent and the Grenadines': 'USD',
  'Samoa': 'USD',
  'San Marino': 'USD',
  'Sao Tome and Principe': 'USD',
  'Saudi Arabia': 'USD',
  'Senegal': 'USD',
  'Serbia': 'USD',
  'Seychelles': 'USD',
  'Sierra Leone': 'USD',
  'Singapore': 'USD',
  'Sint Maarten (Dutch Part)': 'USD',
  'Sistema Unitario de Compensacion Regional de Pagos "Sucre"': 'USD',
  'Slovakia': 'USD',
  'Slovenia': 'USD',
  'Solomon Islands': 'USD',
  'Somalia': 'USD',
  'South Africa': 'USD',
  'South Georgia and the South Sandwich Islands': 'USD',
  'South Sudan': 'USD',
  'Spain': 'USD',
  'Sri Lanka': 'USD',
  'Sudan (The)': 'USD',
  'Suriname': 'USD',
  'Svalbard and Jan Mayen': 'USD',
  'Swaziland': 'USD',
  'Sweden': 'USD',
  'Switzerland (WIR Euro)': 'USD',
  'Switzerland (Swiss Franc)': 'USD',
  'Switzerland (WIR Franc)': 'USD',
  'Syrian Arab Republic': 'USD',
  'Taiwan (Province of China)': 'USD',
  'Tajikistan': 'USD',
  'Tanzania, United Republic of Tanzania': 'USD',
  'Thailand': 'USD',
  'Timor-Leste': 'USD',
  'Togo': 'USD',
  'Tokelau': 'USD',
  'Tonga': 'USD',
  'Trinidad and Tobago': 'USD',
  'Tunisia': 'USD',
  'Turkey': 'USD',
  'Turkmenistan': 'USD',
  'Turks and Caicos Islands': 'USD',
  'Tuvalu': 'USD',
  'Uganda': 'USD',
  'Ukraine': 'USD',
  'United Arab Emirates (The)': 'USD',
  'United Kingdom': 'USD',
  'United States': 'USD',
  'United States of America (The)': 'USD',
  'United States of America (The) (US Dollar Next day)': 'USD',
  'Uruguay (Uruguay Peso en Unidades Indexadas - URUIURUI)': 'USD',
  'Uruguay (Peso Uruguayo)': 'USD',
  'Uzbekistan': 'USD',
  'Vanuatu': 'USD',
  'Venezuela, Bolivarian Republic of Venezuela': 'USD',
  'Venezuela (Bolivarian Republic of)': 'USD',
  'Vietnam': 'USD',
  'Virgin Islands, British': 'USD',
  'Virgin Islands, U.S.': 'USD',
  'Wallis and Futuna': 'USD',
  'Western Sahara': 'USD',
  'Yemen': 'USD',
  'Zambia': 'USD',
  'Zimbabwe': 'USD',
  'Aland Islands': 'USD',
};
