// File: android/build.gradle

// plugins {
//     // Android Gradle Plugin — available to subprojects only
//     id "com.android.application"      version "7.2.0" apply false
//     // Kotlin Android plugin
//     id "org.jetbrains.kotlin.android" version "2.0.20" apply false
//     // Google Services (Firebase) plugin
//     id "com.google.gms.google-services" version "4.3.15" apply false
// }

allprojects {
   
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

subprojects { project ->
  // only apply to Android‐Kotlin modules
  project.plugins.withId("org.jetbrains.kotlin.android") {
    project.tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
      kotlinOptions {
        // make this match your compileOptions targetCompatibility
        jvmTarget = "17"
      }
    }
  }


}