#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/home/smartdev/fvm/versions/3.10.1"
export "FLUTTER_APPLICATION_PATH=/home/smartdev/Documents/business-bosses--v2"
export "FLUTTER_ROOT=C:\Users\pc\fvm\versions\stable"
export "FLUTTER_APPLICATION_PATH=C:\xampp\htdocs\flutter\business-bosses--v2"
export "FLUTTER_ROOT=/home/zarah/dev/flutter"
export "FLUTTER_APPLICATION_PATH=/home/zarah/dev/projects/mobile/flutter/business_bosses_v2"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.dart_tool/package_config.json"
