class CountryCodes {
  static const Map<String, String> codeToName = <String, String>{
    'US': 'United States',
    'CA': 'Canada',
    'GB': 'United Kingdom',
    'DE': 'Germany',
    'FR': 'France',
    'IT': 'Italy',
    'ES': 'Spain',
    'NL': 'Netherlands',
    'SE': 'Sweden',
    'CH': 'Switzerland',
    'NO': 'Norway',
    'DK': 'Denmark',
    'FI': 'Finland',
    'BE': 'Belgium',
    'AT': 'Austria',
    'GR': 'Greece',
    'PT': 'Portugal',
    'IE': 'Ireland',
    'RU': 'Russia',
    'CN': 'China',
    'IN': 'India',
    'JP': 'Japan',
    'KR': 'South Korea',
    'ID': 'Indonesia',
    'SA': 'Saudi Arabia',
    'TR': 'Turkey',
    'TH': 'Thailand',
    'VN': 'Vietnam',
    'MX': 'Mexico',
    'BR': 'Brazil',
    'AR': 'Argentina',
    'CO': 'Colombia',
    'ZA': 'South Africa',
    'EG': 'Egypt',
    'NG': 'Nigeria',
    'KE': 'Kenya',
    'IL': 'Israel',
    'AU': 'Australia',
    'NZ': 'New Zealand',
    'CL': 'Chile',
    'PE': 'Peru',
    'VE': 'Venezuela',
    'EC': 'Ecuador',
    'UY': 'Uruguay',
    'PY': 'Paraguay',
    'BO': 'Bolivia',
    'CR': 'Costa Rica',
    'PA': 'Panama',
    'DO': 'Dominican Republic',
    'CU': 'Cuba',
    'JM': 'Jamaica',
    'PH': 'Philippines',
    'SG': 'Singapore',
    'MY': 'Malaysia',
    'BD': 'Bangladesh',
    'PK': 'Pakistan',
    'IR': 'Iran',
    'IQ': 'Iraq',
    'DZ': 'Algeria',
    'MA': 'Morocco',
    'TN': 'Tunisia',
    'AE': 'United Arab Emirates',
    'QA': 'Qatar',
    'UA': 'Ukraine',
    'CZ': 'Czechia',
    'RO': 'Romania',
    'HU': 'Hungary',
    'SK': 'Slovakia',
    'HR': 'Croatia',
    'BG': 'Bulgaria',
    'RS': 'Serbia',
    'SI': 'Slovenia',
    'LT': 'Lithuania',
    'LV': 'Latvia',
    'EE': 'Estonia',
    'IS': 'Iceland',
    'LU': 'Luxembourg',
    'MT': 'Malta',
    'CY': 'Cyprus',
    'JO': 'Jordan',
    'LB': 'Lebanon',
    'OM': 'Oman',
    'KW': 'Kuwait',
    'LK': 'Sri Lanka',
    'NP': 'Nepal',
    'KH': 'Cambodia',
    'MN': 'Mongolia',
    'KZ': 'Kazakhstan',
    'UZ': 'Uzbekistan',
    'GH': 'Ghana',
    'CI': 'Ivory Coast',
    'SN': 'Senegal',
    'CM': 'Cameroon',
    'UG': 'Uganda',
    'TZ': 'Tanzania',
    'ZW': 'Zimbabwe',
    'NA': 'Namibia',
    'ET': 'Ethiopia',
    'SD': 'Sudan',
    'AO': 'Angola',
    'MZ': 'Mozambique',
  };

  // Optional: Reverse map for name-to-code lookup
  static final Map<String, String> nameToCode =
      codeToName.map((String code, String name) => MapEntry(name, code));
}
